### ISSUE TITLE
Data processing is very slow, with multiple rules/processers

### ISSUE THREAD

**Issue by onejgordon** [echomobi/echo-sense#31]
As an example, a batch of 5 records and a task checking against 5 rules, and 5 processing expressions routinely takes 20-40 seconds.

**Comment by onejgordon** [comment]
Logs below show how slow the _run_processer step is. This with only 6 records:

20:40:41.060
_run_processer - {u'column': u'total_distance', u'calculation': u'. + DISTANCE({location})', u'analysis_key_pattern': u'%SID_%Y-%M-%D'} (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/workers.py:257)
20:40:41.350
total_distance -> 430216 (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/models.py:1099)
20:40:41.351
_run_processer - {u'column': u'n_speeding', u'calculation': u'. + COUNT(ALARMS(5768755258851328))', u'analysis_key_pattern': u'%SID_%Y-%M-%D'} (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/workers.py:257)
20:40:43.628
n_speeding -> 10 (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/models.py:1099)
20:40:43.628
_run_processer - {u'calculation': u'. + COUNT(ALARMS(5703128158568448))', u'column': u'n_accel', u'analysis_key_pattern': u'%SID_%Y-%M-%D'} (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/workers.py:257)
20:40:45.856
n_accel -> 2 (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/models.py:1099)
20:40:45.857
_run_processer - {u'calculation': u'. + COUNT(ALARMS(5669283816275968))', u'column': u'n_braking', u'analysis_key_pattern': u'%SID_%Y-%M-%D'} (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/workers.py:257)
20:40:48.138
n_braking -> 27 (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/models.py:1099)
20:40:48.138
_run_processer - {u'calculation': u'. + (DOT(DELTA({ts}), {ign}) / 1000)', u'column': u'work_secs', u'analysis_key_pattern': u'%SID_%Y-%M-%D'} (/base/data/home/apps/s~echo-sense/0-56.394341286843308748/workers.py:257)

**Comment by onejgordon** [comment]
@cymox1 do you have capacity to look at this this week? Still seeing very slow processing and the issue will increase in severity each day we add new devices.

**Comment by cymox1** [comment]
@onejgordon I will look it at tomorrow and see if I can crack it

**Comment by onejgordon** [comment]
@cymox1 have you had any time to look at this yet? We're still seeing very slow running processing tasks (5 minutes) on even very small batches. I'd like to improve this in any way possible before we do any additional installs.

**Comment by cymox1** [comment]
Sorry @onejgordon, been unable to concentrate long enough to get moving on this but I will get started on this today, will let you know how it goes.
