### ISSUE TITLE
Show more page not responding on manage > Targets

### ISSUE THREAD

**Issue by lissete** [echomobi/echo-sense#82]
@onejgordon I have been able to reproduce it, this is the target tab:
http://sense.echomobile.org/app/manage
issue initially created via #1152

**Comment by onejgordon** [comment]
@lissete I've seen the issue and will fix the UI bug. Note that you can search for targets using the search widget in the left bar, and make changes in the target detail that appears. Does that work for your current use-case?

**Comment by lissete** [comment]
@onejgordon unfortunately target name cannot be edited from this window, so relying on the bug fix for this. Use case is to rename the target as it was wrongly uploaded.
![image](https://cloud.githubusercontent.com/assets/20437943/22774793/c5c41d9a-eeb9-11e6-9dec-9ed814fc7cad.png)
