### ISSUE TITLE
Data viewer page form errors

### ISSUE THREAD

**Issue by lissete** [echomobi/echo-sense#87]
On Echo Sense, while in the data viewer page on a sensor, one cannot view historical data neither can one view details eg location
![image](https://cloud.githubusercontent.com/assets/20437943/22924396/fb33aee6-f2b5-11e6-9983-9204af74661a.png)

**Comment by onejgordon** [comment]
Those are just warnings on the right. Is it possible there's no data in the window selected for that sensor?
